// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhmzPRGr7pruoNtIf41DQVESg1_4oyOg',
    appId: '1:918618014601:web:1b553fd86948ae547d9758',
    messagingSenderId: '918618014601',
    projectId: 'assignment5-d0f4b',
    authDomain: 'assignment5-d0f4b.firebaseapp.com',
    storageBucket: 'assignment5-d0f4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHxPo_YJuTd6ffAeSWRMaYEnurjZhLwo',
    appId: '1:918618014601:android:e79a5328f3b056297d9758',
    messagingSenderId: '918618014601',
    projectId: 'assignment5-d0f4b',
    storageBucket: 'assignment5-d0f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgWS6AW-PwupgcIjKTNVnnLhuYU-V-ng',
    appId: '1:918618014601:ios:10caf8469f7993bc7d9758',
    messagingSenderId: '918618014601',
    projectId: 'assignment5-d0f4b',
    storageBucket: 'assignment5-d0f4b.firebasestorage.app',
    iosBundleId: 'com.example.cocktailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgWS6AW-PwupgcIjKTNVnnLhuYU-V-ng',
    appId: '1:918618014601:ios:10caf8469f7993bc7d9758',
    messagingSenderId: '918618014601',
    projectId: 'assignment5-d0f4b',
    storageBucket: 'assignment5-d0f4b.firebasestorage.app',
    iosBundleId: 'com.example.cocktailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhmzPRGr7pruoNtIf41DQVESg1_4oyOg',
    appId: '1:918618014601:web:e07731dd2b74dc227d9758',
    messagingSenderId: '918618014601',
    projectId: 'assignment5-d0f4b',
    authDomain: 'assignment5-d0f4b.firebaseapp.com',
    storageBucket: 'assignment5-d0f4b.firebasestorage.app',
  );
}
