name: manga_journal
description: A manga reading journal with ML Kit text recognition.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
